// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCMDGoPIa4p9wKVDeTcVuGQiDYSj4T97Y',
    appId: '1:859604804193:web:6fc743ad8082e7fc870020',
    messagingSenderId: '859604804193',
    projectId: 'wrteam-bffe8',
    authDomain: 'wrteam-bffe8.firebaseapp.com',
    storageBucket: 'wrteam-bffe8.appspot.com',
    measurementId: 'G-Q3FJ9C5RNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmp9rCj64MIsT7zbqKj0KXmC5_vJ8vCE',
    appId: '1:859604804193:android:0f6095556eda0fac870020',
    messagingSenderId: '859604804193',
    projectId: 'wrteam-bffe8',
    storageBucket: 'wrteam-bffe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAUfFigDFmp3cx6I5ywQ5mVP-6fzDSKe0',
    appId: '1:859604804193:ios:4b9ca92972ab3a26870020',
    messagingSenderId: '859604804193',
    projectId: 'wrteam-bffe8',
    storageBucket: 'wrteam-bffe8.appspot.com',
    iosBundleId: 'com.example.wrteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAUfFigDFmp3cx6I5ywQ5mVP-6fzDSKe0',
    appId: '1:859604804193:ios:f2970560a8055acd870020',
    messagingSenderId: '859604804193',
    projectId: 'wrteam-bffe8',
    storageBucket: 'wrteam-bffe8.appspot.com',
    iosBundleId: 'com.example.wrteam.RunnerTests',
  );
}
